# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 18) do

  create_table "categories", :force => true do |t|
    t.column "name",       :string
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  create_table "divisions", :force => true do |t|
    t.column "league_id",  :integer
    t.column "name",       :string
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  create_table "events", :force => true do |t|
    t.column "title",       :string
    t.column "body",        :text
    t.column "date",        :datetime
    t.column "updated_at",  :datetime
    t.column "created_at",  :datetime
    t.column "category_id", :integer
  end

  create_table "forums", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
    t.column "updated_at",  :datetime
    t.column "created_at",  :datetime
    t.column "position",    :integer
  end

  create_table "games", :force => true do |t|
    t.column "league_id",    :integer
    t.column "division_id",  :integer
    t.column "team1_id",     :integer
    t.column "team2_id",     :integer
    t.column "scheduled_at", :datetime
  end

  create_table "globalize_countries", :force => true do |t|
    t.column "code",                   :string, :limit => 2
    t.column "english_name",           :string
    t.column "date_format",            :string
    t.column "currency_format",        :string
    t.column "currency_code",          :string, :limit => 3
    t.column "thousands_sep",          :string, :limit => 2
    t.column "decimal_sep",            :string, :limit => 2
    t.column "currency_decimal_sep",   :string, :limit => 2
    t.column "number_grouping_scheme", :string
  end

  add_index "globalize_countries", ["code"], :name => "index_globalize_countries_on_code"

  create_table "globalize_languages", :force => true do |t|
    t.column "iso_639_1",             :string,  :limit => 2
    t.column "iso_639_2",             :string,  :limit => 3
    t.column "iso_639_3",             :string,  :limit => 3
    t.column "rfc_3066",              :string
    t.column "english_name",          :string
    t.column "english_name_locale",   :string
    t.column "english_name_modifier", :string
    t.column "native_name",           :string
    t.column "native_name_locale",    :string
    t.column "native_name_modifier",  :string
    t.column "macro_language",        :boolean
    t.column "direction",             :string
    t.column "pluralization",         :string
    t.column "scope",                 :string,  :limit => 1
  end

  add_index "globalize_languages", ["iso_639_1"], :name => "index_globalize_languages_on_iso_639_1"
  add_index "globalize_languages", ["iso_639_2"], :name => "index_globalize_languages_on_iso_639_2"
  add_index "globalize_languages", ["iso_639_3"], :name => "index_globalize_languages_on_iso_639_3"
  add_index "globalize_languages", ["rfc_3066"], :name => "index_globalize_languages_on_rfc_3066"

  create_table "globalize_translations", :force => true do |t|
    t.column "type",                :string
    t.column "tr_key",              :string
    t.column "table_name",          :string
    t.column "item_id",             :integer
    t.column "facet",               :string
    t.column "built_in",            :boolean
    t.column "language_id",         :integer
    t.column "pluralization_index", :integer
    t.column "text",                :text
    t.column "namespace",           :string
  end

  add_index "globalize_translations", ["tr_key", "language_id"], :name => "index_globalize_translations_on_tr_key_and_language_id"
  add_index "globalize_translations", ["table_name", "item_id", "language_id"], :name => "globalize_translations_table_name_and_item_and_language"

  create_table "leagues", :force => true do |t|
    t.column "name",       :string
    t.column "year",       :date
    t.column "season",     :string
    t.column "active",     :boolean
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  create_table "moderatorships", :force => true do |t|
    t.column "forum_id", :integer
    t.column "user_id",  :integer
  end

  create_table "monitorships", :force => true do |t|
    t.column "topic_id", :integer
    t.column "user_id",  :integer
    t.column "active",   :boolean
  end

  create_table "news_items", :force => true do |t|
    t.column "title",        :string
    t.column "body",         :text
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "published_at", :datetime
  end

  create_table "poll_options", :force => true do |t|
    t.column "option",  :string
    t.column "poll_id", :integer
  end

  create_table "polls", :force => true do |t|
    t.column "description", :text
    t.column "updated_at",  :datetime
    t.column "created_at",  :datetime
  end

  create_table "posts", :force => true do |t|
    t.column "created_at", :date
    t.column "updated_at", :date
    t.column "body",       :text
    t.column "forum_id",   :integer
    t.column "topic_id",   :integer
  end

  create_table "sinks", :force => true do |t|
    t.column "name",         :string
    t.column "body",         :text
    t.column "updated_at",   :datetime
    t.column "created_at",   :datetime
    t.column "status",       :string
    t.column "attachment",   :string
    t.column "shiny",        :boolean
    t.column "protected_by", :string
    t.column "style",        :string
    t.column "washed_at",    :datetime
    t.column "purchased_on", :date
  end

  create_table "teams", :force => true do |t|
    t.column "league_id",   :integer
    t.column "division_id", :integer
    t.column "name",        :string
  end

  create_table "todos", :force => true do |t|
    t.column "description", :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "position",    :integer
    t.column "done",        :boolean
  end

  create_table "topics", :force => true do |t|
    t.column "title",      :string
    t.column "forum_id",   :integer
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "name",                      :string
  end

end
