# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

desc "Run lib specs"
Spec::Rake::SpecTask.new('speclib') do |t|
  t.spec_files = FileList[File.dirname(__FILE__)+'/../roar/spec/**/*.rb']
end

 
desc "Run Watir"
Spec::Rake::SpecTask.new('watir') do |t|
  t.spec_files = FileList['spec/integration/*.rb']
  t.spec_opts = ['--require', 'spec/spec_helper'] #, '--format', 'html'
  #t.out = "#{report_dir}/report.html"
end

report_dir = File.expand_path(File.dirname(__FILE__) + '/report')

desc "Run Watir with html output"
Spec::Rake::SpecTask.new('watirhtml') do |t|
  t.spec_files = FileList['spec/integration/*.rb']
  t.spec_opts = ['--require', 'spec/spec_helper', '--format', 'html']
  t.out = "#{report_dir}/report.html"
end

# spec/ui screenshots 
# task :clean_report do
#   img_dir = "#{report_dir}/images"
#   ENV['RSPEC_IMG_DIR'] = img_dir
#   FileUtils.rm_rf(report_dir) if File.exist?(report_dir)
#   FileUtils.mkdir_p(img_dir)
# end
# 
# task :watir => :clean_report

task :stats => "statsintegrationsetup"

desc "Setup specs for stats"
task :statsintegrationsetup do
  require 'code_statistics'
  ::STATS_DIRECTORIES << %w(Integration\ specs spec/integration)
  ::CodeStatistics::TEST_TYPES << "Integration specs"
end
